# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_url', models.URLField(unique=True, verbose_name='the user url')),
                ('url_code', models.CharField(max_length=6, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('nike_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='user nike name')),
                ('nb_access', models.IntegerField(default=0)),
            ],
        ),
    ]
